import { Telegraf, Markup } from 'telegraf'; import { prisma, assertListingTransition } from '@board/core';
const tokenValue=process.env.TELEGRAM_BOT_TOKEN; const appUrlValue=process.env.TELEGRAM_MINI_APP_URL; const usernameValue=process.env.TELEGRAM_BOT_USERNAME; if(!tokenValue||!appUrlValue||!usernameValue)throw new Error('TELEGRAM_BOT_TOKEN, TELEGRAM_BOT_USERNAME and TELEGRAM_MINI_APP_URL are required'); const token:string=tokenValue; const appUrl:string=appUrlValue; const botUsername:string=usernameValue;
const bot=new Telegraf(token); const privateBoard=()=>Markup.inlineKeyboard([Markup.button.webApp('Открыть доску',appUrl)]); const publicBoard=()=>Markup.inlineKeyboard([Markup.button.url('Открыть доску',`https://t.me/${botUsername}?start=board`)]);
bot.start(ctx=>ctx.reply('Добро пожаловать на доску объявлений сообщества.',privateBoard())); bot.command('board',ctx=>ctx.reply('Открыть объявления:',ctx.chat.type==='private'?privateBoard():publicBoard())); bot.command('help',ctx=>ctx.reply('/board — открыть доску\n/myads — мои объявления\n/rules — правила'));
bot.command('rules',async ctx=>{const c=await prisma.community.findFirst({where:{isActive:true}});await ctx.reply(c?.rules||'Правила сообщества пока не опубликованы.');});
bot.command('myads',ctx=>ctx.reply('Ваши объявления доступны в профиле Mini App.',Markup.inlineKeyboard([Markup.button.webApp('Мои объявления',`${appUrl}?screen=my-listings`)])));
const roles=new Set(['moderator','admin','owner']); async function moderator(telegramId:number,communityId:string){return prisma.communityMember.findFirst({where:{communityId,user:{telegramUserId:BigInt(telegramId),status:'active'},role:{in:[...roles] as any}}});}
bot.action(/^mod:(approve|changes|reject|ban):(.+)$/,async ctx=>{const [,action,id]=ctx.match;const listing=await prisma.listing.findUnique({where:{id},include:{author:true}});if(!listing||!await moderator(ctx.from.id,listing.communityId)){await ctx.answerCbQuery('Недостаточно прав',{show_alert:true});return;}if(action==='ban'){await prisma.$transaction([prisma.user.update({where:{id:listing.authorId},data:{status:'banned'}}),prisma.moderationAction.create({data:{communityId:listing.communityId,moderatorId:(await moderator(ctx.from.id,listing.communityId))!.userId,targetUserId:listing.authorId,listingId:id,action:'user_banned'}})]);await ctx.answerCbQuery('Пользователь заблокирован');return;}if(action==='changes'||action==='reject'){await ctx.editMessageReplyMarkup({inline_keyboard:[['Запрещённый товар','Недостаточно информации','Некорректная категория','Подозрение на мошенничество','Дубликат','Некачественные фотографии','Нарушение правил'].map((r,i)=>({text:r,callback_data:`reason:${action}:${i}:${id}`}))]});await ctx.answerCbQuery('Выберите причину');return;}assertListingTransition(listing.status,'published');const mod=await moderator(ctx.from.id,listing.communityId);await prisma.$transaction([prisma.listing.update({where:{id},data:{status:'published',publishedAt:new Date(),moderatedAt:new Date(),moderatedById:mod!.userId}}),prisma.moderationAction.create({data:{communityId:listing.communityId,moderatorId:mod!.userId,listingId:id,action:'listing_approved'}}),prisma.notification.create({data:{communityId:listing.communityId,userId:listing.authorId,type:'listing_published',payload:{listingId:id}}})]);await ctx.editMessageCaption(`✅ Одобрено модератором ${ctx.from.first_name}\n${new Date().toLocaleString('ru')}`).catch(()=>ctx.editMessageText(`✅ Одобрено модератором ${ctx.from.first_name}`));await ctx.answerCbQuery('Одобрено');});
const reasons=['Запрещённый товар','Недостаточно информации','Некорректная категория','Подозрение на мошенничество','Дубликат','Некачественные фотографии','Нарушение правил'];
bot.action(/^reason:(changes|reject):(\d+):(.+)$/,async ctx=>{const [,kind,index,id]=ctx.match;const listing=await prisma.listing.findUnique({where:{id}});if(!listing)return ctx.answerCbQuery('Уже обработано');const mod=await moderator(ctx.from.id,listing.communityId);if(!mod)return ctx.answerCbQuery('Недостаточно прав',{show_alert:true});const to=kind==='changes'?'changes_requested':'rejected';assertListingTransition(listing.status,to);const reason=reasons[Number(index)];await prisma.$transaction([prisma.listing.update({where:{id},data:{status:to,moderationComment:reason,moderatedAt:new Date(),moderatedById:mod.userId}}),prisma.moderationAction.create({data:{communityId:listing.communityId,moderatorId:mod.userId,listingId:id,action:kind==='changes'?'changes_requested':'listing_rejected',reason}}),prisma.notification.create({data:{communityId:listing.communityId,userId:listing.authorId,type:`listing_${to}`,payload:{listingId:id,reason}}})]);await ctx.editMessageText(`${to==='rejected'?'❌ Отклонено':'✏️ На доработку'}: ${reason}\nМодератор: ${ctx.from.first_name}`);await ctx.answerCbQuery('Решение сохранено');});
async function poll(){const pending=await prisma.notification.findMany({where:{status:'pending'},include:{user:true},take:20});for(const n of pending){try{if(n.user)await bot.telegram.sendMessage(n.user.telegramUserId.toString(),notificationText(n.type,n.payload as any),Markup.inlineKeyboard([Markup.button.webApp('Открыть',appUrl)]));await prisma.notification.update({where:{id:n.id},data:{status:'sent',sentAt:new Date(),attempts:{increment:1}}});}catch(e){await prisma.notification.update({where:{id:n.id},data:{status:'failed',attempts:{increment:1},lastError:String((e as Error).message).slice(0,500)}});}}}
function notificationText(type:string,p:any){const reason=p?.reason?`\nПричина: ${p.reason}`:'';return ({listing_published:'Ваше объявление одобрено.',listing_rejected:'Ваше объявление отклонено.',listing_changes_requested:'Ваше объявление требует изменений.',listing_interest:'Вашим объявлением заинтересовались.'} as any)[type]+reason||'Новое уведомление';}
const timer=setInterval(()=>void poll(),5000);bot.launch();process.once('SIGTERM',()=>{clearInterval(timer);bot.stop('SIGTERM');void prisma.$disconnect();});
